### PR TITLE
fix affiliations and dois in refs

### PR DESCRIPTION
**Pull request by fred-atherden**

### CODE REVIEW

**Comment by scottaubrey** [comment]
Hi @FAtherden-eLife ,

It's quite hard to see because of sporadic xml entity replacements in there, but is the list of changes:
- all:
  - change `<ext-link ext-link-type="uri" xlink:href="https://doi.org/{doi}">https://doi.org/{doi}</ext-link>` to `<pub-id pub-id-type="doi">{doi}</pub-id>`
- 10.1101/2022.05.30.22275761
  - remove `<sec sec-type="supplementary-material"></sec>` block
- 10.1101/2022.07.26.501569
  - change `, Ecole Polytechnique F&#x00E9;d&#x00E9;rale de Lausanne` to `</institution>, Ecole Polytechnique F&#x00E9;d&#x00E9;rale de Lausanne</institution>`

**Comment by FAtherden-eLife** [comment]
@scottaubrey, yep, that's right :+1:

**Comment by scottaubrey** [comment]
@FAtherden-eLife Great - I've automated those changes [here ](https://github.com/elifesciences/enhanced-preprints-data/pull/4), which will make this more easily reproducable (and allow reimport if we make other fixes).

Would you be OK to take a quick look over the diff and see if you're OK with that instead of this one?

**Comment by FAtherden-eLife** [comment]
@scottaubrey, sorry, one more thing (which I forgot) needs changing in `2022.05.30.22275761.xml` in #4:
```xml
<contrib contrib-type="author" corresp="yes">
<contrib-id contrib-id-type="orcid">http://orcid.org/0000-0002-6973-5385</contrib-id>
<name><surname>Kankaanp&#x00E4;&#x00E4;</surname><given-names>Anna</given-names></name>
<degrees>MSc</degrees>
<xref ref-type="corresp" rid="cor1">&#x002A;</xref>
</contrib>
```

to:
```xml
<contrib contrib-type="author" corresp="yes">
<contrib-id contrib-id-type="orcid">http://orcid.org/0000-0002-6973-5385</contrib-id>
<name><surname>Kankaanp&#x00E4;&#x00E4;</surname><given-names>Anna</given-names></name>
<degrees>MSc</degrees>
<xref ref-type="aff" rid="a1">1</xref>
<xref ref-type="corresp" rid="cor1">&#x002A;</xref>
</contrib>
```

(Adding `<xref ref-type="aff" rid="a1">1</xref>`), so that the affiliation for the first author is present.

**Comment by scottaubrey** [comment]
Pushed an update to the other PR to automate that too. Is that OK now?

**Comment by FAtherden-eLife** [comment]
Looks good - thanks

**Comment by scottaubrey** [comment]
merged #4 instead

**Pull request closed without merging**
